-- AlterTable
ALTER TABLE `i_BuildingLevel` MODIFY `Wood` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    MODIFY `Food` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    MODIFY `Stone` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    MODIFY `Currency` INTEGER UNSIGNED NOT NULL DEFAULT 0;

